### ISSUE TITLE
<div> as an interactive element

### ISSUE THREAD

**Issue by MeLoveCarbs** [OSU-NLP-Group/SeeAct#38]
Hi, first of all thank you so much for developing this amazing web agent. After looking through the code, I do have a question. It seems that `<div>` tag is filtered out from interactive element and occasionally, some `<div>` buttons isn't pressed because it isn't retrieved as an interactive element. I also understand that there is a huge amount of div tags in modern webpages, could this be the reason why it is left out?

**Comment by boyugou** [comment]
Overall, it's not easy to correctly and efficiently filter every interactive element. That's why we maintained a list of possible interactive element selectors.

I have tried to include every element before, but it turns out GPT often chooses to click on pure text elements. If there is a better interactive element retrieving strategy, feel free to tell us or make a PR. Thanks for your understanding.

**Comment by MeLoveCarbs** [comment]
That makes sense, I will help out and look into it too. Closing this issue for now.
